[package]
name = "x_ai"
version = "0.0.1"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/x_ai.rs"

[features]
default = []
schemars = ["dep:schemars"]

[dependencies]
anyhow.workspace = true
futures.workspace = true
http_client.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
workspace-hack.workspace = true
